# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-20 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20180120_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
